config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#index'
  get 'contact', to: 'static_pages#contact', as: 'contact'
  get 'team', to: 'static_pages#team', as: 'team'
  get 'login', to: 'static_pages#login', as: 'login'
  get 'welcome/:id', to: 'static_pages#welcome', as: 'welcome'


  resources :users do
    resources :loans
    resources :reservations
  end


  resources :events do
    resources :comments
  end
  
  resources :cities, only: [:index, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :books 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

    belongs_to :invited, class_name: "User"
    belongs_to :event
  
  end

app/models/book.rb
class Book < ApplicationRecord

  
    belongs_to :category 
  
    has_many :rservations 
    has_many :users, through: :reservation
    has_many :loans
    has_many :tags
    has_many :libraries
end

app/models/category.rb
class Category < ApplicationRecord

    has_many :books 
end

app/models/city.rb
class City < ApplicationRecord

    has_many :users 
    has_many :libraries
    has_many :events

end

app/models/comment.rb
class Comment < ApplicationRecord
    acts_as_votable

    belongs_to :user 
    belongs_to :event 

    has_many :recomments

end

app/models/event.rb
class Event < ApplicationRecord

belongs_to :city 
has_many :comments
has_many :attendances
has_many :inviteds, class_name: 'User',  through: :attendances
belongs_to :admin, :foreign_key => :admin_id, class_name: 'User'

end

app/models/library_list.rb
class LibraryList < ApplicationRecord
    has_many :books
    belongs_to :city 
end

app/models/loan.rb
class Loan < ApplicationRecord

    belons_to :book
    ha_many :users         
    end
    
end

app/models/recomment.rb
class Recomment < ApplicationRecord

     belongs_to :comment
     has_many :users 

end

app/models/reservation.rb
class Reservation < ApplicationRecord

    has_many :books 
    has_many :users 
end

app/models/tag.rb
class Tag < ApplicationRecord

    belongs_to :category 
    has_many :books 
end

app/models/user.rb
class User < ApplicationRecord
has_secure_password
acts_as_voter

  belongs_to :city
  has_many :reservations 
  has_many :loans 
  has_many :comments 
  has_many :recomments 
  has_many :events,foreign_key: 'admin_id',  dependent: :destroy
  has_many :attendances, foreign_key: 'invited_id' , dependent: :destroy

  validates :email, uniqueness: true
  
end

app/models/vote.rb
class Vote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    #before_action :authenticate_user, except: [:index]
  
    def index
         @events=Event.all.order(date: :ASC)
    end
  
    def show  
        @event=Event.find_by(id:"#{params[:id]}")
        @comments=Comment.where(event_id:"#{params[:id]}")
        @user_data=@event.user_id  
        @user=User.find_by(id:"#{@user_data}")
        @present=Attendance.where(event_id: @event)
      
    end
  
    def new
       # @user_id = current_user.id
        @event = Event.new
    end
  
    def create  
        @event= Event.new(title: params[:title],
            description: params[:description],
            date: params[:date],
            city_id: params[:city_id],
            user_id: 2 
            )
      if @event.save
        redirect_to event_path
      else
        render new_event_path
      end
    end
  
    # def vote
    #   set_gossip
    #   if !current_user.liked? @gossip
    #     @gossip.upvote_from current_user
    #   else
    #     @gossip.downvote_from current_user
    #   end
    #   redirect_to request.referrer
  
    def edit  # Pour custom ton histoire, direction le salon de l'edit. De quoi te rappeler tes week-ends tuning avec Jackie et sa super dedeuch tunée à souhait !
      #set_gossip
    end
  
    def update  # Une fois que tu as choisi quoi tuner, on y met un ptit coup de polish.
    #   set_gossip
    #   gossip_params = params.require(:gossip).permit(:title, :content)
    #   @gossip.update(gossip_params)
    #   redirect_to gossip_path
    end
  
    def destroy # Suppresion d'un gossip. Mieux qu'un rollback.
    #   set_gossip
    #   @gossip.destroy
    #   redirect_to gossips_path
    end
end
  
    # private
  
#     def set_gossip
#       @gossip = Gossip.find(params[:id])
#     end
#   end
  

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    before_action :authenticate_user, only: [:welcome]
  
    def index # landing page
    end
  
    def contact # ET téléphone maison
    end
  
    def team  # The Super Fuck Friends
    end
  
    def welcome # Welcome screen
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #before_action :authenticate_user, except: [:index]
  
    def index
    end
  
    def show 
        @user=User.find(params[:id])
        @events=Event.where(user_id:"#{params[:id]}")
    end
  
    def new

        puts params 
        
        #@new_user=Users.new()

    end
  
    def create  # Fonction appelée lors de la création d'un gossip.
    #   @new_gossip = Gossip.new(user_id: current_user.id, title: params['gossip_title'], content: params['gossip_content'])
  
    #   if @new_gossip.save
    #     redirect_to gossips_path
    #   else
    #     render new_gossip_path
    #   end
    # end
  
    # def vote
    #   set_gossip
    #   if !current_user.liked? @gossip
    #     @gossip.upvote_from current_user
    #   else
    #     @gossip.downvote_from current_user
    #   end
    #   redirect_to request.referrer
     end
  
    def edit  # Pour custom ton histoire, direction le salon de l'edit. De quoi te rappeler tes week-ends tuning avec Jackie et sa super dedeuch tunée à souhait !
      #set_gossip
    end
  
    def update  # Une fois que tu as choisi quoi tuner, on y met un ptit coup de polish.
    #   set_gossip
    #   gossip_params = params.require(:gossip).permit(:title, :content)
    #   @gossip.update(gossip_params)
    #   redirect_to gossip_path
    end
  
    def destroy # Suppresion d'un gossip. Mieux qu'un rollback.
    #   set_gossip
    #   @gossip.destroy
    #   redirect_to gossips_path
    end
end
  
    # private
  
#     def set_gossip
#       @gossip = Gossip.find(params[:id])
#     end
#   end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.erb
	<div class="container">
        <div class="card-header col-lg-12 d-flex m-0 p-0 rounded text-center bg-info text-white", width=100%>
        <h2 class="py-2 text-center"  style="display: inline-block"><span class="text-warning pl-3"><%= Event.all.count%></span> events vous attendent</h2> 
        <a class="  ml-auto p-1 mt-3 mr-2 btn btn-outline-warning btn-lg " href="<%=new_event_path%>" role="button" style="display: inline-block; height:35px; font-size:15px">Create new event</a>
        </div>


        <div class="body mt-4" style="display:flex-wrap:wrap; width:100%; height:auto">
                <% @events.each do |event| %> 
                    <div  class="col-12" style="flex-wrap:wrap height:150px; align-self:flex-start;" >
                        <div class="card col-md-12 bg-light colo box-shadow border-secondary" style="margin-bottom:3vh; height:120px; display: block;">
                            <div class="card-body">
                                <h5 class="card-title font-weight-bold playfair-relative"> <%= event.title.capitalize %> <span class="badge badge-success"><%= Comment.where(event: event.id).count %> <i class="far fa-comment-dots fa-sm"></i></span></h5>
                                <div class="row">
                                    <div class="col">
                                        <p class="card-text text-danger"> <%= event.date %></p>
                                    </div>

                                    <div class="col text-right">
                                        <%= link_to "Read more about this event  ##{event.id}", event_path(event.id), :class => " btn btn-outline-success" %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                 <% end %>
        </div>
        </div>

app/views/events/new.html.erb
<div class="container">

<center>
<div class="card border-primary justify-content-center  bg-light col-md-8 m-2">
    <div class="card-header  bg-info text-light col-lg-12 p-1 mt-3 mb-4"><h2 class="text-center mt-2"> Créer un événement </h2></div>

            <%= form_tag url_for(action: 'create'), method: "Post" do %>

            <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>

             <div class="card-body font-weight-bold justify-content-center text-left ">

                        <div class="form-group">
                        <%= label_tag 'Title' %>
                        <%= text_field_tag 'title', @event.title, class: 'form-control' %>
                        </div>

                        <div class="form-group">
                        <%= label_tag 'Description' %>
                        <%= text_field_tag 'description', @event.description, class: 'form-control' %>
                        </div>

                        <div class="form-group">
                        <%= label_tag 'Date' %>
                        <%= date_field_tag (:date, Date.today, class: 'form-control')%>
                        </div>

                        <div class="form-group">
                        <%= label_tag 'Lieu' %>
                        <%= text_field_tag 'city_id', @event.city_id, class: 'form-control' %>
                        </div>

                        <%= submit_tag "Publier", class:'btn btn-info col-md-4 btn-submit' %>
                        <% end %>
</div>
</div>
                      
                </center>

</div>

app/views/events/show.html.erb
<div class="container">

<div class="card border-secondary col-md-8 offset-md-2 p-0">
<div class="card-header col-lg-12 d-flex m-0 p-0 rounded text-center bg-danger text-white", width=100%>
<h2 class="py-2"  style="display: inline-block; padding-left:15px"> Event</h2> 
<a class=" ml-auto p-1 mt-2 mr-2 btn btn-primary btn-lg " href="#" role="button" style="display: inline-block; height:35px; font-size:15px">Subscribe</a>
</div>
<div class="card-body px-0 py-3 mx-0 my-1">

      <div class="row text-left  justify-content-center">
        <div class="col-4"> <p class="font-weight-bold">Title:</p></div><div class="col-6"><p class="text-primary font-italic"><%= @event.title%></p></div>
      </div>

      <div class="row text-left  justify-content-center">
        <div class="col-4"> <p class="font-weight-bold">Created by:</p></div><div class="col-6"><%= link_to "#{@user.user_name}", user_path(@user), :class => "badge badge-success" %></div>
      </div>

      <div class="row text-left  justify-content-center">
        <div class="col-4"> <p class="font-weight-bold">Date:</p></div><div class="col-6"><p class="text-danger font-italic"><%= @event.date%></div>
      </div>

      <div class="row text-left  justify-content-center">
        <div class="col-4"> <p class="font-weight-bold">Lieu:</p></div><div class="col-6"><p class="text-primary font-italic"><%= @event.city %></p></div>
      </div>

      <div class="row text-left  justify-content-center">
        <div class="col-4"> <p class="font-weight-bold">Nombre des Participants: </p></div><div class="col-6"><p class="text-primary font-italic"><%=@present.all.count %></p></div>
      </div>

      <div class="row text-left  justify-content-center">
        <div class="col-4"> <p class="font-weight-bold">Description:</p></div><div class="col-6"> <p><%=@event.description%></p></div>
     </div>
</div>
</div>


<div class="content">
<br/>
<div style=" background-color:rgba(247,208,158, 0.5); margin:auto; padding-left:15px; padding-top:10px; padding-bottom:10px">
<h3> Commentes</h3>
</div>
<div class="body mt-4" style="display:flex-wrap:wrap; width:100%; height:auto text-left">
                <% @comments.each do |comment| %> 
                    <div  class="col-10 offset-1" style="flex-wrap:wrap height:150px; align-self:flex-start; background-color:orange" >
                        <div class="card col-md-12 bg-light colo box-shadow border-secondary" style="margin-bottom:3vh; height:auto; display: block;">
                            <div class="card-body">
                                <h6 class="card-title font-weight-bold playfair-relative"> <%= comment.title.capitalize %></h6>
                                <div class="row">
                                    <div class="col">
                                        <p class="card-text text-success"> <%=comment.user.first_name%>,<%=comment.user.last_name%><span class="text-dark"> at</span><span class="card-text text-danger"> <%=comment.created_at %></span></p>
                                       <p class="card-text"> <%=comment.content%></p>

                                    <div class="col text-right mr-0 p-0">
                                        <a class="mt-1 p-1 btn  btn-outline-info" href="#" role="button" style="height:30px; font-size:15px">Recomment</a>
                                    </div>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                 <% end %>
        </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>

  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a href="<%= root_path %>" class="navbar-brand"><b> Library</b></a>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button> 

  <div class="collapse navbar-collapse ml-3" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a href="<%= books_path %>"class="nav-link">Catalogue<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a href="<%= events_path %>" class="nav-link">Events</a>
      </li>
      <li class="nav-item">
        <a href="<%= team_path %>" class="nav-link">Team</a>
      </li>
      <li class="nav-item">
        <a href="<%= contact_path %>" class="nav-link">Contact</a>
      </li></ul>
  </div>
  <form class="dropdown-menu p-4">
  <div class="form-group">
    <label for="exampleDropdownFormEmail2">Email address</label>
    <input type="email" class="form-control" id="exampleDropdownFormEmail2" placeholder="email@example.com">
  </div>
  <div class="form-group">
    <label for="exampleDropdownFormPassword2">Password</label>
    <input type="password" class="form-control" id="exampleDropdownFormPassword2" placeholder="Password">
  </div>
  <div class="form-check">
    <input type="checkbox" class="form-check-input" id="dropdownCheck2">
    <label class="form-check-label" for="dropdownCheck2">
      Remember me
    </label>
  </div>
  <button type="submit" class="btn btn-primary">Sign in</button>
</form>
</nav>


    <%= yield %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<div class="container">
      <h3>Pour nous cantacter Merci de rempir le formulaire et l'envoyer</h3>
      <p>bien evidemment pour qu'on puisse te repondre, il nous faut ton adresse mail  😉  </p>
<form>
  <div class="form" style="display: inline-block">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for="first_name">First name:</label>
    <div class="col-sm-4" style="display: inline-block">
      <input type="text" class="first_name" placeholder="Nasim">
    </div>
    <div class="form2">
    <label for="last_name">Last name:</label>
    <div class="col-sm-4" style="display: inline-block">
      <input type="text" class="last_name"placeholder="Ibrahimi">
    </div>
  </div>
  <div class="form3">
    <label for="email" style="display: inline-block" >Email add: </label>
    <div class="col-sm-4" style="display: inline-block">
      <input type="text" class="email" placeholder="exemple@exemple.com">
    </div>
  </div>
  <br>
  <div class="from4">
  <textarea  class="col-sm-6 name="message" form="message" rows="10" cols="150" placeholder="Enter your message"></textarea><br><br>
   </div>
  <div class="form-group row">
    <div class="col-sm-2">
      <button type="submit" class="btn btn-primary">Envoyer</button>
    </div>
  </div>
</form>
</div>

app/views/static_pages/index.html.erb
<div class="container">
  <h1 class="text-center">Welcome to our online library </h1>
  <h4 class="text-center text-danger">This site is under construction for this moment</h4>


<section class="d-flex justify-content-center mt-5">

  <button type="submit" style="width:150px" class="btn btn-primary mr-5"><a href="<%= new_user_path %>" class="text-decoration-none font-weight-bold text-light">S'inscrire</a></button>

  <button type="submit" style="width:150px"  class="btn btn-primary mr-5"><a href="<%= new_session_path %>" class="text-decoration-none font-weight-bold text-light">Se connecter</a></button>

</section>
</div>

app/views/static_pages/team.html.erb
<div class="container">
  <h1 class="text-center mt-5">Notre équipe</h1>
  <h4 class="text-center mt-3 mb-5"><b>Nous sommmes à votre disposition!</b></h4>
</section>

<section class="d-flex justify-content-around flex-row mt-5">

<div class="card bg-light mb-3" style="max-width: 18rem;">
  <img src="https://blog.galvanize.com/wp-content/uploads/2018/03/20150708172005-coding-working-workspace-apple-macintosh.jpg" class="card-img-top" alt="naismIbrahimi">
  <div class="card-header text-center"><h5><b>Nasim IBRAHIMI</b></h5></div>
  <div class="card-body">
    <p class="card-title"><strong> Responsable du site WEB</strong></p>
    <p class="card-text">Email: <a href="mailto:nasim_ebi@yahoo.com">nasim_ebi@yahoo.com</a></p>
  </div>
</div>
<div class="card bg-light mb-3" style="max-width: 18rem;">
  <img src="https://edito.regionsjob.com/observatoire-metier/wp-content/uploads/sites/4/2015/12/d%C3%A9veloppeur-web.jpg" class="card-img-top" alt="naismIbrahimi">
  <div class="card-header text-center"><h5><b>Nasim IBRAHIMI</b></h5></div>
  <div class="card-body">
    <p class="card-title"><strong> Responsable du site WEB</strong></p>
    <p class="card-text">Email: <a href="mailto:nasim_ebi@yahoo.com">nasim_ebi@yahoo.com</a></p>
  </div>
</div>
<div class="card bg-light mb-3" style="max-width: 18rem;">
  <img src="https://cdn.uclouvain.be/styles/full_content/groups/cms-editors-digitalu/HommeTabletteCafe-Pexels.jpg?itok=iXkNjCD5" class="card-img-top" alt="naismIbrahimi">
  <div class="card-header text-center"><h5><b>Nasim IBRAHIMI</b></h5></div>
  <div class="card-body">
    <p class="card-title"><strong> Responsable du site WEB</strong></p>
    <p class="card-text">Email: <a href="mailto:nasim_ebi@yahoo.com">nasim_ebi@yahoo.com</a></p>
  </div>
</div>
</div>

app/views/static_pages/welcome.html.erb
<h1 class="text-center mt-5">Bienvenue <%= current_user.username %></h1>

<h6 class="text-center mt-5"> J'espère que tu as bien préparé tes histoires les plus salaces, parce-qu'ici,<br/> <span class="text-danger"> on ne fait pas dans le potin fin.</span> </h6>

app/views/users/new.html.erb
  <div class="container">

<center>
<div class="card border-secondary col-md-5 m-2">
    <div class="card-header col-lg-12 p-2 mb-2 mt-3 bg-danger text-white"><h2>Sign up</h2></div>

  <%= form_for :users do |f| %>    

  <div class="card-body font-weight-bold ">
    <div class="form-group">
      <div class="field justify-content-center">
          <%= f.label :first_name, style:" control-label", class:"col-md-7 text-left mt-1" %><br/>
          <%= f.first_name:first_name, autofocus: true,class:"col-md-7 form-control", autocomplete: "first name" %>
        </div>
          <div class="field justify-content-center">
          <%= f.label :last_name, style:" control-label", class:"col-md-7 text-left mt-1" %><br/>
          <%= f.lastname_field :last_name, autofocus: true,class:"col-md-7 form-control", autocomplete: "last name" %>
        </div>
          <div class="field justify-content-center">
          <%= f.label :user_name, style:" control-label", class:"col-md-7 text-left mt-1" %><br/>
          <%= f.username_field :user_name, autofocus: true,class:"col-md-7 form-control", autocomplete: "user name" %>
        </div>

        <div class="field justify-content-center">
          <%= f.label :email, style:" control-label", class:"col-md-7 text-left mt-1" %><br/>
          <%= f.email_field :email, autofocus: true,class:"col-md-7 form-control", autocomplete: "email" %>
        </div>

        <div class="field justify-content-center">
          <%= f.label :password , style:" control-label", class:"col-md-7 text-left mt-1"%>
          <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %><br />
          <%= f.password_field :password,class:"col-md-7 form-control", autocomplete: "new-password" %>
        </div>

        <div class="field justify-content-center">
          <%= f.label :password_confirmation, style:" control-label", class:"col-md-7 text-left mt-1" %><br/>
          <%= f.password_field :password_confirmation, class:"col-md-7 form-control",autocomplete: "new-password" %>
        </div>

        <div class="actions row d-flex justify-content-around col-md-12"">
          <%= f.submit "Sign up",  class:"btn btn-outline-success col-md-3 mt-1", style:"display:inline-block"%>
        </div>
      <% end %>
      </div>
      </div>
      <center>
      </div>

app/views/users/show.html.erb
<div class="container col-12">

<div class="card border-secondary row col-8 offset-2 p-0" style="display: inline-block">
<h3 class="col-12 p-3 m-0 bg-success text-white text-center"> Profile de <span class="text-warning"><%=@user.user_name%></span></h3> 
<div class="row">
<div class="card-body col-8 px-0 py-3 mx-0 my-1">

      <div class="row text-left  justify-content-center">
        <div class="col-4"> <p class="font-weight-bold">First name:</p></div><div class="col-6"><p class="text-primary font-italic"><%= @user.first_name%></p></div>
      </div>

      <div class="row text-left  justify-content-center">
        <div class="col-4"> <p class="font-weight-bold">Last name:</p></div><div class="col-6"><p class="text-primary font-italic"><%= @user.last_name%></p></div>
      </div>

      <div class="row text-left  justify-content-center">
        <div class="col-4"> <p class="font-weight-bold">Date of birth:</p></div><div class="col-6"><p class="text-danger font-italic"><%= @user.birth_date%></div>
      </div>

      <div class="row text-left  justify-content-center">
        <div class="col-4"> <p class="font-weight-bold">Email:</p></div><div class="col-6"><p class="text-primary font-italic"><%= @user.mail %></p></div>
      </div>

      <div class="row text-left  justify-content-center">
        <div class="col-4"> <p class="font-weight-bold">Address:</p></div><div class="col-6"><p class="text-primary font-italic"><%= @user.city.name %></p></div>
      </div>

</div>
<div class="d-flex col-4 justify-content-center align-items-center ">
  <i class="fas fa-user-alt fa-10x"></i>
</div>
</div>
</div>
<div class="card border-secondary row col-8 offset-2 p-0" style="display: inline-block">
<h5 class="col-12 p-3 m-0 bg-success text-white font-weight-bold">La liste des événements crées par ce memebre </h5>
<div class="body mt-1" style="display:flex-wrap:wrap; width:100%; height:auto text-left">
                <% @events.each do |event| %> 
                            <div class="card-body m-0  py-1">
                             <h6><%= link_to "#{event.title.capitalize}", event_path(event.id), :class => "card-title font-weight-bolds"%></h6>
                                <p class="card-text text-success" style="border-bottom: 1px solid green"> <%=event.date%> </p>
                            </div>
                 <% end %>
        </div>
</div>